<?php

namespace MorenoRafael\LaravelPayment\Facades;

use Illuminate\Support\Facades\Facade;

class LaravelPayment extends Facade
{
    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}